name: Update Visits

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  update-visits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Increment visit counter
        id: increment
        run: |
          # Initialize visits.txt if it doesn't exist
          if [ ! -f visits.txt ]; then echo "0" > visits.txt; fi
          # Read current count and increment
          visits=$(cat visits.txt)
          visits=$((visits + 1))
          echo $visits > visits.txt
          echo "::set-output name=visits::$visits"

      - name: Update README.md
        run: |
          visits=${{ steps.increment.outputs.visits }}
          badge="![Visits](https://img.shields.io/badge/Visits-$visits-blue)"
          sed -i 's|!\[Visits\](https://img.shields.io/badge/Visits-.*-blue)|'"$badge"'|' README.md

      - name: Commit changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Configure git for GitHub Actions
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add visits.txt README.md
          git commit -m 'Update visits count'
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sudoesjudo/automation.git HEAD:main
